-- =============================================================================
-- BANCO DE DADOS: CONCILIACAO_BANCARIA (SQL SERVER / AZURE SQL)
-- Case Técnico: Desenvolvedor de Automação
-- Candidato: Diego Luiz Lino de Aquino
-- Data: 2026-09-21
-- =============================================================================

USE master;
GO

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'CONCILIACAO_BANCARIA')
BEGIN
    CREATE DATABASE CONCILIACAO_BANCARIA;
END;
GO

USE CONCILIACAO_BANCARIA;
GO

-- 1. TABELA PRINCIPAL DE CONCILIAÇÃO
IF OBJECT_ID('TB_CONCILIACAO_BANCARIA', 'U') IS NULL
BEGIN
    CREATE TABLE TB_CONCILIACAO_BANCARIA (
        ID_TRANSACAO INT IDENTITY(1,1) PRIMARY KEY,
        ID_EXTERNO NVARCHAR(100) NOT NULL,
        BANCO NVARCHAR(50) NOT NULL,
        CONTA NVARCHAR(30) NOT NULL,
        DATA_TRANSACAO DATETIME NOT NULL,
        VALOR DECIMAL(15, 2) NOT NULL,
        DESCRICAO NVARCHAR(500) NOT NULL,
        TIPO NVARCHAR(20) DEFAULT 'Débito',
        CATEGORIA NVARCHAR(50) NULL,
        STATUS_CONCILIACAO NVARCHAR(30) DEFAULT 'Pendente', -- Pendente, Conciliado, Discrepância
        FLAG_DISCREPANCIA BIT DEFAULT 0,
        MOTIVO_DISCREPANCIA NVARCHAR(500) NULL,
        IA_NIVEL_RISCO NVARCHAR(20) NULL, -- Baixo, Médio, Alto
        IA_ACAO_RECOMENDADA NVARCHAR(1000) NULL,
        IA_CONFIANCA DECIMAL(5, 4) NULL,
        CORRELATION_ID NVARCHAR(100) NULL,
        DATA_PROCESSAMENTO DATETIME DEFAULT GETDATE(),
        DATA_ATUALIZACAO DATETIME DEFAULT GETDATE(),
        CONSTRAINT UK_EXTERNO_BANCO_CONTA UNIQUE(ID_EXTERNO, BANCO, CONTA)
    );
END;
GO

-- 2. ÍNDICES DE ALTA PERFORMANCE PARA O DASHBOARD E JOINS
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_CONC_BANCO_DATA')
    CREATE NONCLUSTERED INDEX IDX_CONC_BANCO_DATA ON TB_CONCILIACAO_BANCARIA(BANCO, DATA_TRANSACAO DESC);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_CONC_DISCREPANCIA')
    CREATE NONCLUSTERED INDEX IDX_CONC_DISCREPANCIA ON TB_CONCILIACAO_BANCARIA(FLAG_DISCREPANCIA) INCLUDE (VALOR, BANCO, STATUS_CONCILIACAO);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IDX_CONC_CORRELATION')
    CREATE NONCLUSTERED INDEX IDX_CONC_CORRELATION ON TB_CONCILIACAO_BANCARIA(CORRELATION_ID);
GO

-- 3. TABELA DE AUDITORIA CONTÁBIL (SOX COMPLIANT)
IF OBJECT_ID('TB_AUDITORIA_CONCILIACAO', 'U') IS NULL
BEGIN
    CREATE TABLE TB_AUDITORIA_CONCILIACAO (
        ID_AUDITORIA INT IDENTITY(1,1) PRIMARY KEY,
        ID_TRANSACAO INT NOT NULL,
        ACAO NVARCHAR(20) NOT NULL, -- INSERT, UPDATE, AUDIT_IA
        VALORES_ANTERIORES NVARCHAR(MAX) NULL,
        VALORES_NOVOS NVARCHAR(MAX) NULL,
        USUARIO_SISTEMA NVARCHAR(100) DEFAULT SYSTEM_USER,
        CORRELATION_ID NVARCHAR(100) NULL,
        DATA_AUDITORIA DATETIME DEFAULT GETDATE(),
        FOREIGN KEY (ID_TRANSACAO) REFERENCES TB_CONCILIACAO_BANCARIA(ID_TRANSACAO)
    );
END;
GO

-- 4. VIEW ANALÍTICA: RESUMO DIÁRIO POR BANCO (CONSUMIDA PELO POWER BI)
CREATE OR ALTER VIEW VW_RESUMO_DIARIO AS
SELECT
    CAST(DATA_TRANSACAO AS DATE) AS DATA_REFERENCIA,
    BANCO,
    COUNT(*) AS TOTAL_TRANSACOES,
    SUM(VALOR) AS VOLUME_TOTAL,
    SUM(CASE WHEN FLAG_DISCREPANCIA = 1 THEN 1 ELSE 0 END) AS QTD_DISCREPANCIAS,
    SUM(CASE WHEN FLAG_DISCREPANCIA = 0 THEN 1 ELSE 0 END) AS QTD_CONCILIADAS,
    CAST(
        (SUM(CASE WHEN FLAG_DISCREPANCIA = 0 THEN 1 ELSE 0 END) * 100.0) / NULLIF(COUNT(*), 0) 
        AS DECIMAL(5,2)
    ) AS TAXA_ACURACIA_PCT
FROM TB_CONCILIACAO_BANCARIA
GROUP BY CAST(DATA_TRANSACAO AS DATE), BANCO;
GO

-- 5. VIEW ANALÍTICA: CONSOLIDAÇÃO EXECUTIVA (ÚLTIMOS 30 DIAS)
CREATE OR ALTER VIEW VW_CONSOLIDACAO_BANCO AS
SELECT
    BANCO,
    COUNT(*) AS TOTAL_OPERACOES,
    SUM(VALOR) AS VOLUME_TOTAL_R$,
    AVG(VALOR) AS TICKET_MEDIO_R$,
    MAX(VALOR) AS MAIOR_LANCAMENTO_R$,
    SUM(CASE WHEN VALOR > 100000 THEN 1 ELSE 0 END) AS QTD_OPERACOES_ACIMA_100K,
    SUM(CASE WHEN FLAG_DISCREPANCIA = 1 THEN 1 ELSE 0 END) AS TOTAL_DISCREPANCIAS
FROM TB_CONCILIACAO_BANCARIA
WHERE DATA_TRANSACAO >= DATEADD(DAY, -30, GETDATE())
GROUP BY BANCO;
GO

-- 6. STORED PROCEDURE: DETECÇÃO AUTOMATIZADA DE DISCREPÂNCIAS
CREATE OR ALTER PROCEDURE SP_DETECTAR_DISCREPANCIAS
    @DIAS_ATRAS INT = 1,
    @CORRELATION_ID NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    -- REGRA 1: Teto de Alçada (> R$ 100.000,00)
    UPDATE TB_CONCILIACAO_BANCARIA
    SET FLAG_DISCREPANCIA = 1,
        STATUS_CONCILIACAO = 'Discrepância',
        MOTIVO_DISCREPANCIA = 'Valor crítico excedendo o teto de R$ 100.000,00',
        DATA_ATUALIZACAO = GETDATE()
    WHERE VALOR > 100000.00
      AND DATA_TRANSACAO >= DATEADD(DAY, -@DIAS_ATRAS, GETDATE())
      AND FLAG_DISCREPANCIA = 0;

    -- REGRA 2: Outliers Estatísticos (> 2 Desvios Padrão da Média Histórica)
    ;WITH EstatisticasBanco AS (
        SELECT 
            BANCO,
            AVG(VALOR) AS MEDIA_VALOR,
            STDEV(VALOR) AS DESVIO_VALOR
        FROM TB_CONCILIACAO_BANCARIA
        WHERE DATA_TRANSACAO >= DATEADD(DAY, -90, GETDATE())
        GROUP BY BANCO
        HAVING COUNT(*) >= 10
    )
    UPDATE T
    SET T.FLAG_DISCREPANCIA = 1,
        T.STATUS_CONCILIACAO = 'Discrepância',
        T.MOTIVO_DISCREPANCIA = 'Valor estatisticamente superior a 2 desvios-padrão da média',
        T.DATA_ATUALIZACAO = GETDATE()
    FROM TB_CONCILIACAO_BANCARIA T
    INNER JOIN EstatisticasBanco E ON T.BANCO = E.BANCO
    WHERE T.DATA_TRANSACAO >= DATEADD(DAY, -@DIAS_ATRAS, GETDATE())
      AND T.VALOR > (E.MEDIA_VALOR + (2 * ISNULL(E.DESVIO_VALOR, 0)))
      AND T.FLAG_DISCREPANCIA = 0;

    -- REGRA 3: Transações Idênticas com Mesma Conta e Valor no mesmo dia (Potencial Duplicata)
    ;WITH DuplicatasPotenciais AS (
        SELECT 
            ID_TRANSACAO,
            ROW_NUMBER() OVER (
                PARTITION BY BANCO, CONTA, VALOR, CAST(DATA_TRANSACAO AS DATE) 
                ORDER BY ID_TRANSACAO
            ) AS OCORRENCIA
        FROM TB_CONCILIACAO_BANCARIA
        WHERE DATA_TRANSACAO >= DATEADD(DAY, -@DIAS_ATRAS, GETDATE())
    )
    UPDATE T
    SET T.FLAG_DISCREPANCIA = 1,
        T.STATUS_CONCILIACAO = 'Discrepância',
        T.MOTIVO_DISCREPANCIA = 'Potencial duplicata (mesmo banco, conta, valor e data)',
        T.DATA_ATUALIZACAO = GETDATE()
    FROM TB_CONCILIACAO_BANCARIA T
    INNER JOIN DuplicatasPotenciais D ON T.ID_TRANSACAO = D.ID_TRANSACAO
    WHERE D.OCORRENCIA > 1
      AND T.FLAG_DISCREPANCIA = 0;

    -- Registrar Execução da Procedure na Auditoria
    INSERT INTO TB_AUDITORIA_CONCILIACAO (ID_TRANSACAO, ACAO, VALORES_NOVOS, CORRELATION_ID)
    SELECT TOP 1 
        ID_TRANSACAO, 
        'SP_DISCREPANCIA', 
        CONCAT('Detecção executada. Total de discrepâncias: ', (SELECT COUNT(*) FROM TB_CONCILIACAO_BANCARIA WHERE FLAG_DISCREPANCIA = 1)),
        @CORRELATION_ID
    FROM TB_CONCILIACAO_BANCARIA;

    -- Retornar resultado em JSON para consumo direto do Power Automate
    SELECT 
        ID_TRANSACAO,
        ID_EXTERNO,
        BANCO,
        CONTA,
        CONVERT(VARCHAR(19), DATA_TRANSACAO, 120) AS DATA_TRANSACAO,
        VALOR,
        DESCRICAO,
        MOTIVO_DISCREPANCIA
    FROM TB_CONCILIACAO_BANCARIA
    WHERE FLAG_DISCREPANCIA = 1
      AND DATA_TRANSACAO >= DATEADD(DAY, -@DIAS_ATRAS, GETDATE())
    FOR JSON AUTO;
END;
GO
